### ISSUE TITLE
Still frame doesnt show

### ISSUE THREAD

**Issue by lawloretienne** [rubensousa/PreviewSeekBar#1] opened 2017-01-27 20:24 UTC
So I tried integrating the PreviewSeekBar based on the usage in your readme but i dont see the still frame showing.  How do I fix this?

**Comment by rubensousa** [comment] 2017-01-28 00:32
That's a very vague description. Can you provide a code example?
Are you using a custom LoadControl and TrackSelection like the sample app is?

**Comment by lawloretienne** [comment] 2017-01-28 01:02
I am using what the sample shows in Usage 
https://github.com/rubensousa/PreviewSeekBar#create-a-player-with-a-custom-trackselection-and-loadcontrol
I can see the preview frame shows when the progressbar changes but an image never loads in the ExoPlayer view.  I noticed that you call `ExoPlayer.seekTo()` followed by `ExoPlayer.setPlayWhenReady(false);`. This second statement prevents the exoplayer from playing and is essentially the same as pause.  Is this part of the issue?

**Comment by rubensousa** [comment] 2017-01-28 01:16
I use ```setPlayWhenReady(false)``` to force a pause. Otherwise, the video would keep playing inside the preview frame. Although I'm not sure if it's really needed. 

Are you using the exact attributes as here? I got that issue when I was using a surfaceview.

```xml
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
    android:id="@+id/previewPlayerView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:controller_layout_id="@layout/exo_simple_player_view"
    app:surface_type="texture_view"
    app:use_artwork="false"
    app:use_controller="false" />
```

I won't have time to investigate this now. If you come up with a solution, let me know.

**Comment by rubensousa** [comment] 2017-02-03 13:41
Did you fix this?

**Comment by rubensousa** [comment] 2017-03-13 15:52
@lawloretienne, any updates on this issue?

**Comment by lawloretienne** [comment] 2017-03-13 16:11
sorry I haven't had time to look into this issue. I've been busy lately.

**Comment by rubensousa** [comment] 2017-07-25 19:59
Any updates on this or can I close it? I was never able to reproduce it.

**Comment by rubensousa** [comment] 2017-12-13 13:59
I'm going to close this since it's not relevant for the current implementation. Thumbnails are now fetched from a thumbnail sprite.

**Closed by rubensousa** 2017-12-13 13:59 UTC
Labels: needs info
